#include "constant.h"
#include "spmv_bdia.cl"
#include "spmv_dia.cl"
#include "spmv_sbell.cl"
#include "spmv_bell.cl"
#include "spmv_bcsr.cl"
#include "spmv_sell.cl"
#include "spmv_ell.cl"
#include "spmv_csr_vector.cl"
#include "spmv_csr_scalar.cl"
#include "spmv_coo.cl"
#include "mem_bandwidth.cl"

